version: '3'

services:
  backend:
    build: ./
    command: gunicorn worddombot.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - react_build:/var/www/react
    depends_on:
      - backend
