# Generated by Django 3.1.2 on 2020-10-29 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('thousand', models.PositiveSmallIntegerField(verbose_name='Tanlangan minglik')),
                ('quizzes', models.TextField(verbose_name='Tanlangan savollar tartib raqamlari')),
                ('found', models.BooleanField(default=False, verbose_name='Raqib topilgan')),
                ('finished', models.BooleanField(default=False, verbose_name='Bellashuv yakunlangan')),
            ],
            options={
                'verbose_name': 'Bellashuv',
                'verbose_name_plural': 'Bellashuvlar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=32, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Tartib raqami')),
                ('first', models.PositiveSmallIntegerField(verbose_name="Biriktirilgan birinchi so'z tartib raqami")),
                ('last', models.PositiveSmallIntegerField(verbose_name="Biriktirilgan oxirgi so'z tartib raqami")),
                ('description', models.TextField(verbose_name="Daraja haqida ma'lumot")),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='Foydalanuvchi IDsi')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('energy', models.IntegerField(default=30, verbose_name='⚡️')),
                ('step', models.PositiveSmallIntegerField(null=True)),
                ('data', models.TextField(null=True)),
                ('is_member', models.BooleanField(default=True, verbose_name="Kanalga a'zo")),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Tartib raqami')),
                ('word', models.CharField(max_length=128, verbose_name="So'z")),
                ('translation', models.CharField(max_length=512, verbose_name='Tarjima')),
                ('variants', models.TextField(help_text='Variantlarni vergul(,) bilan ajratib yozing', verbose_name='Variantlar')),
                ('pronunciation', models.CharField(max_length=128, verbose_name='Talaffuz qilinish')),
                ('synonyms', models.CharField(max_length=512, verbose_name='Sinonimlar')),
                ('example', models.TextField(verbose_name="So'zga misol")),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='bot.book', verbose_name='Kitob')),
            ],
            options={
                'verbose_name': "So'z",
                'verbose_name_plural': "So'zlar",
            },
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('diamonds', models.PositiveSmallIntegerField(default=0, verbose_name='Brilliantlar miqdori')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to='bot.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xamyon',
                'verbose_name_plural': 'Xamyonlar',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('answers', models.TextField(default='', verbose_name='Javoblar')),
                ('started_time', models.DateTimeField(null=True, verbose_name='Boshlangan vaqti')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Tugagan vaqti')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bot.battle', verbose_name='Bellashuv')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='bot.user', verbose_name='Qatnashchi')),
            ],
            options={
                'verbose_name': 'Qatnashchi',
                'verbose_name_plural': 'Qatnashchilar',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.CharField(max_length=256, verbose_name='Savol')),
                ('answer', models.CharField(max_length=100, verbose_name="To'g'ri javob")),
                ('variants', models.TextField(help_text='Variantlarni vergul(,) bilan ajratib yozing', verbose_name='Variantlar')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='bot.word', verbose_name="So'z")),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='bot.book', verbose_name='Kitob'),
        ),
    ]
