# Generated by Django 3.1.2 on 2020-10-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pronunciation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
    ]
