# Generated by Django 3.1.2 on 2020-10-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201029_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='question',
            field=models.TextField(help_text="Yangi qatorlarni qanday kiritsangiz shunday ko'rinadi", verbose_name='Savol'),
        ),
    ]
