# Generated by Django 3.1.2 on 2020-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20201030_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='variants',
            field=models.TextField(blank=True, help_text='Variantlarni vergul(,) bilan ajratib yozing', null=True, verbose_name='Variantlar'),
        ),
    ]
