# Generated by Django 3.1.2 on 2020-11-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201030_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='bot.word', verbose_name="So'z"),
        ),
    ]
