# Generated by Django 3.1.2 on 2020-12-14 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20201101_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64, verbose_name='Nomi')),
                ('token', models.CharField(max_length=256, verbose_name='Token')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktiv'), (False, 'No aktiv')], default=False, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Provayder',
                'verbose_name_plural': 'Provayderlar',
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='with_friend',
            field=models.BooleanField(default=False, verbose_name="Do'st bilan"),
        ),
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='bot.user', verbose_name='Taklif etuvchi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=6, verbose_name='\U0001f7e1'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('thousand', models.PositiveSmallIntegerField(verbose_name='Minglik')),
                ('hundred', models.PositiveSmallIntegerField(verbose_name='Yuzlik')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='bot.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='bot.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bot.provider', verbose_name="To'lov operatori")),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bot.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_id', models.CharField(help_text='Kanal IDsini olish uchun kanaldagi biron xabarni @ShowJsonBot ga yuboring', max_length=32, verbose_name='IDsi')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('link', models.CharField(help_text='https://t.me bilan boshlanuvchi manzil', max_length=256, verbose_name='Manzil')),
                ('required', models.BooleanField(choices=[(True, 'Ha'), (False, "Yo'q")], default=False, verbose_name="Doim a'zo bo'lish talab etiladimi ?")),
                ('is_active', models.BooleanField(choices=[(True, 'Ha'), (False, "Yo'q")], default=False, verbose_name='Holati aktivmi?')),
                ('members', models.ManyToManyField(blank=True, related_name='channels', to='bot.User', verbose_name="A'zolar")),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
            },
        ),
    ]
