# Generated by Django 3.1.2 on 2021-01-11 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20201214_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'Text message'), ('1', 'Photo message'), ('2', 'Audio message'), ('3', 'Voice message'), ('4', 'Video message')], max_length=2)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': ' post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
