# Generated by Django 3.1.2 on 2023-03-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Foydalanuvchi IDsi'),
        ),
    ]
